EXE = dos32\gameboy.exe
CC = gcc
CFLAGS = -Ofast -s -DNDEBUG
LDFLAGS = -Ofast -s
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)

$(EXE): $(OBJ)
	$(CC) $^ -o $@ $(LDFLAGS)

%.o: %.c
	$(CC) $< -o $@ -c $(CFLAGS)

clean:
	@del *.o
	@del $(EXE)

