EXE = dos32\gameboy.exe
CC = gcc
CFLAGS = -Ofast -s -DNDEBUG -Wdisabled-optimization --param max-gcse-memory=268435456 -flto
LDFLAGS = -s -Ofast -flto
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)

$(EXE): $(OBJ)
	$(CC) $^ -o $@ $(LDFLAGS)

%.o: %.c
	$(CC) -o $@ -c $< $(CFLAGS)

clean:
	@del *.o
	@del $(EXE)

